### ISSUE TITLE
Problem running the program

### ISSUE THREAD

**Issue by Lukastos** [AlexAndDraw/YVD10#1]
Hi!

I'm also a rather new kivy user and I was just reading your code to get inspired and see how other people build their program.

I couldn't run the program (python 3.5 on linux):

- `File

 "/home/.../YVD10-master/YVD10/player/player.py", line 152
     ]# invokes this method from the active card
     ^
 SyntaxError: invalid syntax`
There is an extra [

- `from player.player import Player
   File "/home/.../YVD10-master/YVD10/player/player.py", line 164
     self.session.send_command(f'COMMANDKEY|CHANGEMODE|{self.active_card.angle}|{key}')
                                                                                     ^
 SyntaxError: invalid syntax`

**Comment by AlexAndDraw** [comment]
Seem it was a typo when I was retroactively adding comments. I'll get onto dealing with it later tonight. I assume you just went in and fixed it in your version?

**Comment by AlexAndDraw** [comment]
Fixed. Thanks for the help!
